### ISSUE TITLE
tqdm=4.31.1 ImportError with pandas=0.25.1

### ISSUE THREAD

**Issue by schwille-paint** [schwille-paint/lbFCS#9]
``` tqdm.pandas()```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/username/.conda/envs/py36/lib/python3.6/site-packages/tqdm/_tqdm.py", line 545, in pandas
    from pandas.core.groupby import PanelGroupBy
ImportError: cannot import name 'PanelGroupBy'

**Comment by schwille-paint** [comment]
Can be solved by updating tqdm to tqdm=36.1
